### PR TITLE
Update to mleap 0.16.0

### PR DESCRIPTION
**Pull request by tschutte**
This pull request updates the mleap version to 0.16.0.

### CODE REVIEW

**Comment by tschutte** [comment]
@kevinykuo, is it possible to have this merged?  Or is there other work needed to make this happen?

**Comment by yitao-li** [comment]
@tschutte Hey sorry for the delay... The change looks good to me :+1: (as in, all tests pass after rebuilding the `inst/java/mleap-*.jar` files with `ml.combust.mleap:mleap-spark_2.11:0.16.0`). Thanks for contributing to mleap!

I'll create another PR that keep the build artifacts from `inst/java/mleap-*.jar` up-to-date.

Kevin is in the process of transferring ownership of https://github.com/rstudio/mleap to me BTW. So I'll be the new maintainer of mleap moving forward.

**Review by yitao-li — APPROVED** [review]
LGTM

**Comment by yitao-li** [comment]
@tschutte FYI please re-run `remotes::install_github("rstudio/mleap")` if you want to start using `mleap` with `ml.combust.mleap:mleap-spark_2.11:0.16.0` immediately (because you will need to replace your local version of `mleap` with the updated jar files from https://github.com/rstudio/mleap/pull/43).

**Comment by tschutte** [comment]
Excellent, thank you again.

**Pull request merged**
